# Refer to golangci-lint's example config fake for more options and information:
# https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml

run:
  timeout: 5m
#  modules-download-mode: readonly

linters:
  enable:
    - errcheck
#    - goimports
    - revive
    - govet
    - staticcheck
  enable-all: false
#  disable:
#    - shadow
  disable-all: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
